Pcv query event suppression
CiscoDevNet/ansible-nae pull request #24
Opened 2020-11-03 07:53 UTC by camrossi

Fix #23

2020-11-06 06:15 UTC, xinyuezhao reviewed
reviewed

2020-11-06 06:15 UTC, xinyuezhao commented on plugins/module_utils/nae.py
>              m = str(x['base_epoch_collection_timestamp'])[:10]
it might be better to remove this empty line or the sanity test may not pass

2020-11-06 06:15 UTC, xinyuezhao commented on plugins/module_utils/nae.py
> +                elif str(x['epoch2_details']['mnemonic']) in suppressed_event_list:
would it be better if we use

if str(x['epoch2_details']['severity']) == "EVENT_SEVERITY_INFO" or str(x['epoch2_details']['mnemonic']) in suppressed_event_list:
                continue

2020-11-06 06:15 UTC, xinyuezhao commented on plugins/modules/nae_prechange.py
> +    required: no
maybe we don't need this line as the default value is no

2020-11-06 22:23 UTC, lhercot requested changes

2020-11-06 22:23 UTC, lhercot commented on plugins/module_utils/nae.py
>              f = self.params['file']
self.params.get('file')

2020-11-06 22:23 UTC, lhercot commented on plugins/module_utils/nae.py
> +            if resp.headers['Content-Encoding'] == "gzip":
resp.headers.get('Content-Encoding')

2020-11-10 07:30 UTC, lhercot commented
There seems to be a conflict with those changes and the new merged codebase. You will need to rebase your changes and resolve the conflict.
Let me or Cindy know if you need help.

2020-11-10 08:29 UTC, lhercot approved these changes

2020-11-10 08:30 UTC, lhercot commented
I fixed the issues reported by Cindy and me, rebased the branch on top of the latest master.
Sanity and Integration now pass so merging this.

2020-11-10 08:30 UTC, merged