[nae_prechange] Add tasks to nae_prechange and add better error message. fixes #2
CiscoDevNet/ansible-nae pull request #39
Opened 2020-12-09 04:29 UTC by anvitha-jain

Resloves isuue #2 by adding tasks to nae_prechange - main.yml and added condition to check epoch value in nae.py and made changes to support the prechange tasks.

2020-12-09 11:30 UTC, lhercot requested changes

2020-12-09 11:30 UTC, lhercot commented on plugins/module_utils/nae.py
> +            # job_id = self.params.get('job_id') # necessary to PUT method
If not need, we should remove it

2020-12-09 11:30 UTC, lhercot commented on tests/integration/targets/nae_prechange/tasks/main.yml
> +    # save: True
Title say save but this line is not

2020-12-09 11:30 UTC, lhercot commented on tests/integration/targets/nae_prechange/tasks/main.yml
> +- name: Verify Addding pre-change analysis from manual changes
Addding -> adding

2020-12-09 11:30 UTC, lhercot commented on tests/integration/targets/nae_prechange/tasks/main.yml
> +    that:
is it changed again or not?

2020-12-11 06:48 UTC, anvitha-jain commented on tests/integration/targets/nae_prechange/tasks/main.yml
> +    that:
no

2020-12-12 08:11 UTC, lhercot requested changes

2020-12-12 08:11 UTC, lhercot commented on plugins/module_utils/nae.py
> +            # self.result['stdout'] = json.loads(r.decode())['value']['data']
lets remove those comments if we don't need them

2020-12-12 08:11 UTC, lhercot commented on plugins/module_utils/nae.py
> +                        # self.params['job_id'] = obj.get('job_id')
Remove comment if not needed

2020-12-15 04:16 UTC, lhercot approved these changes
LGTM

2020-12-15 04:16 UTC, merged